### ISSUE TITLE
CD3- errors and knowledge session  -For Suruchi

### ISSUE THREAD

**Issue by dsilvasu** [oracle-devrel/cd3-automation-toolkit#118]
We have hit a lot of problems with CD3 in one of the OCI tenancy. Suruchi came up n helped us in rectifying all those errors - in one go. Her expertise and dedication to stay back until all our concerns are resolved, are definitely commendable. Many Thanks Suruchi !!

**Comment by xs2suruchi** [comment]
Thank you.
Please keep us posted about any further queries you have via Issues.
