### ISSUE TITLE
Excel template CD3-Blank-template.xlsx invalid tab name causes failure

### ISSUE THREAD

**Issue by cf185056** [oracle-devrel/cd3-automation-toolkit#77]
In the template CD3-Blank-template.xlsx, the tab "NLB-Listeners" is actually "NLB-Listeners " (extra space at the end of the name). This extra space causes the script to fail when exporting NLBs in a non-greenfield setup on the initial run. Once the tab is renamed, the process works.

**Comment by xs2suruchi** [comment]
yes, we removed that in our upcoming release
