### ISSUE TITLE
fatal issue when creating network

### ISSUE THREAD

**Issue by eugsim1** [oracle-devrel/cd3-automation-toolkit#79]
The process fail with the below error

hub-vcn is MARKED AS HUB  (from the examples) 

Enter your choice (specify comma separated to choose multiple choices): 3
=======================================================Network=======================================================
1. Create Network - overwrites all TF files; reverts all SecLists and RouteTables to original rules
2. Modify Network - It will read VCNs, DRGs, SubnetsVLANs and DHCP sheets and update the TF
3. Security Rules
4. Route Rules
5. DRG Route Rules
6. Network Security Groups
7. Add/Modify/Delete VLANs
8. Customer Connectivity
q. Press q to quit
m. Press m to go back to Main Menu
Enter your choice (specify comma separated to choose multiple choices): 1
-------------------------------------------------Create All Objects--------------------------------------------------
--------------------------------------------Process VCNs Tab and DRGs Tab--------------------------------------------
ERROR!!! hub-vcn not marked as Hub. Verify hub_spoke_peer_none column again..Exiting!
[cd3user@9a85eed555b2 cd3_automation_toolkit]$

**Comment by xs2suruchi** [comment]
The error says - "ERROR!!! hub-vcn not marked as Hub. Verify hub_spoke_peer_none column again..Exiting!"
Please check VCNs tab ion your excel sheet. You should mark hub-vcn as 'Hub' in the column.
Thanks
