### ISSUE TITLE
documentation discrepencies please update the setup procedure i m getting all kind of exceptions of wrong permissions !

### ISSUE THREAD

**Issue by eugsim1** [oracle-devrel/cd3-automation-toolkit#82]
Hello
can you please TIDE UP the content of the documentation https://github.com/oracle-devrel/cd3-automation-toolkit/blob/main/cd3_automation_toolkit/documentation/user_guide/Connect_container_to_OCI_Tenancy.md

first its impossible to navigate back and forth between the sections of  the documentation if i try to get the previous page of your documentation im getting the "rw github md pointers"

then i have tried to follow the steps that you are describing in this section : https://github.com/oracle-devrel/cd3-automation-toolkit/blob/main/cd3_automation_toolkit/documentation/user_guide/Connect_container_to_OCI_Tenancy.md

I m getting all kind of permission errors on the directories like

PermissionError: [Errno 13] Permission denied: '/cd3user/tenancies/ES1/oci4cca_api_key_localadmin_07-09-2023.pem' -> '/cd3user/tenancies/ES1/oci4cca_api_key_localadmin_07-09-20  

when then i m trying to give sudo rights i m getting new exceptions as :

PermissionError: [Errno 13] Permission denied: '/cd3user/tenancies/keys_backup_173117'
[

my tenancie.properties is like :

# Path of API Private Key (PEM Key) File; If the PEM keys were generated by running createAPI.py, leave this field empty.
# Defaults to /cd3user/tenancies/keys/oci_api_private.pem when left empty.
key_path=/cd3user/tenancies/keys/oci_api_private.pem

# Region ; defaults to us-ashburn-1 when left empty.
region=eu-frankfurt-1

ls -lrt /cd3user/tenancies/keys/oci_api_private.pem
-rw-r--r--. 1 root root 1703 Jan  8 17:29 /cd3user/tenancies/keys/oci_api_private.pem

its impossible to know what you are using as user to create the files and the structure of the output !!!!!!
i have created the container as :

docker run --platform linux/amd64 --name cd3toolkit -it -d -v /home/oracle/cd3:/cd3user/tenancies  cd3toolkit:v1 
docker container ls --all

and from the beginning i cant run properly the python script python createTenancyConfig.py tenancyconfig.properties
because OF WRONG RIGHTS on the target directories please elaboreate better the steps  !

**Comment by xs2suruchi** [comment]
Where have you launched the docker container? Is it in your local laptop? Or some linux system?

**Comment by eugsim1** [comment]
its running on the OCI as docker instance

**Comment by eugsim1** [comment]
/cd3user/oci_tools/cd3_automation_toolkit/user-scripts
[cd3user@a6737a692c14 user-scripts]$ python createAPIKey.py
Creating Public/Private API PEM Key at /cd3user/tenancies/keys/.......
Traceback (most recent call last):
  File "createAPIKey.py", line 44, in <module>
    create_keys()
  File "createAPIKey.py", line 26, in create_keys
    f = open(keys_dir+"/oci_api_private.pem", "wb")
PermissionError: [Errno 13] Permission denied: '/cd3user/tenancies/keys//oci_api_private.pem'

**Comment by eugsim1** [comment]
t /cd3user/tenancies/keys/.......
Traceback (most recent call last):
  File "createAPIKey.py", line 44, in <module>
    create_keys()
  File "createAPIKey.py", line 20, in create_keys
    os.makedirs(keys_dir)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)

I have removed the keys directory and now im getting this exception

**Comment by eugsim1** [comment]
i had to re create the local directory keys outside of the container as  : mkdir -vp keys chmod ugo+rwx keys to make the code work for the key generation

**Comment by eugsim1** [comment]
[oracle@dev-instance keys]$ ls -lrt
total 8
-r--------. 1 1001 1001 1678 Jan  8 17:58 oci_api_private.pem
-rw-rw-r--. 1 1001 1001  450 Jan  8 17:58 oci_api_public.pem

**Comment by xs2suruchi** [comment]
When u use docker on a linux VM in OCi tenancy, you generally get permission denied error. We have tried to document the steps tp resolve this under point no 8 at - 

https://github.com/oracle-devrel/cd3-automation-toolkit/blob/main/cd3_automation_toolkit/documentation/user_guide/FAQ.md

please let me know if this helps

**Comment by eugsim1** [comment]
from the container

=================================================================
NOTE: Make sure the API Public Key is added to the OCI Console!!!
=================================================================
Using single out directory for resources..........
key_path field is empty or default in tenancyconfig.properties. Using /cd3user/tenancies/keys/oci_api_private.pem
Copying the key files to /cd3user/tenancies/ES1
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/cd3user/tenancies/keys' -> '/cd3user/tenancies/keys_backup_183800'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "createTenancyConfig.py", line 357, in <module>
    seek_info()
  File "createTenancyConfig.py", line 147, in seek_info
    shutil.move(auto_keys_dir, auto_keys_dir + "_backup_" + time.strftime("%H%M%S"))
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/shutil.py", line 807, in move
    copytree(src, real_dst, copy_function=copy_function,
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/shutil.py", line 458, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/cd3user/tenancies/keys_backup_183800'
[cd3user@a6737a692c14 user-scripts]$ ls -lrt /cd3user/tenancies/keys
total 8
-rw-rw-r--. 1 cd3user cd3user  450 Jan  8 18:16 oci_api_public.pem
-r--------. 1 cd3user cd3user 1703 Jan  8 18:18 oci_api_private.pem

the host has already - since its creation disabled the selinux -

[oracle@dev-instance ~]$ sudo getenforce
Disabled
[oracle@dev-instance ~]$


[oracle@dev-instance ~]$ cat  /etc/selinux/config

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=disabled
# SELINUXTYPE= can take one of these three values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected.
#     mls - Multi Level Security protection.
#SELINUXTYPE=minimum

**Comment by eugsim1** [comment]
the steps in the "troubleshooting section" should be expicitly given on the step 1

**Comment by eugsim1** [comment]
Would be possible to create the assets - terraform scripts - with wide permission on the host so i will not need to run chmod , or chown if i want to modify them from the host ?
thanks
